name: Check

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install --global pnpm
          pnpm install

      - name: Run unit tests
        run: pnpm test

      - name: Lint code formatting
        run: pnpm lint:fmt
        if: always()

      - name: Lint CSS
        run: pnpm lint:css
        if: always()
