name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SSH_CONFIG: |
            Host srv
              User kenina
              IdentityFile ~/.ssh/key
              StrictHostKeyChecking no
              HostName kenina.8086.cf
              Port 25565
        run: |
          umask 077

          mkdir -p ~/.ssh
          echo >~/.ssh/key "$SSH_PRIVATE_KEY"
          echo >~/.ssh/config "$SSH_CONFIG"

          rsync -avzP --exclude=/.git/ ./ srv:/var/www/kenina/

      - name: Post notification
        run: >
          curl ntfy.sh/kenina-deploy-status
          -H 'Title: Kenina has been published'
          -H 'Tags: partying_face'
          -H "Actions: view, View site, https://kenina.8086.cf"
          -d 'You have become the boss of the gym.'
